name: Release

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  release-linux-386:
    name: release linux/386
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: wangyoucao577/go-release-action@v1.15
      with:
        goversion: 1.15
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: linux
        goarch: 386